document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("");
document.writeln("    <style>");
document.writeln("        .initial {");
document.writeln("            display: flex;");
document.writeln("            position: fixed;");
document.writeln("            color: red;");
document.writeln("            width: 240px;");
document.writeln("            height: 240px;");
document.writeln("            left: 75%;");
document.writeln("            bottom: 15%;");
document.writeln("");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .image {");
document.writeln("            position: absolute;");
document.writeln("            left: 200px;");
document.writeln("        }");
document.writeln("");
document.writeln("        .change {");
document.writeln("            display: none;");
document.writeln("            position: fixed;");
document.writeln("            color: red;");
document.writeln("            width: 240px;");
document.writeln("            height: 240px;");
document.writeln("            right: 50px;");
document.writeln("            bottom: 50px;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("        .mainbody {");
document.writeln("            position: absolute;");
document.writeln("        }");
document.writeln("");
document.writeln("        .expression {");
document.writeln("            position: absolute;");
document.writeln("        }");
document.writeln("        .face {");
document.writeln("            position: absolute;");
document.writeln("        }");
document.writeln("        .hair {");
document.writeln("            position: absolute;");
document.writeln("        }");
document.writeln("        .talking{");
document.writeln("            position:absolute;");
document.writeln("");
document.writeln("        }");
document.writeln("        .frame{");
document.writeln("            position:absolute;");
document.writeln("            display: none;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("");
document.writeln("   <script type=\'text/javascript\' src=\'movement.js\'>");
document.writeln("");
document.writeln("   </script>");
document.writeln("");
document.writeln("  <script type=\'text/javascript\'>");
document.writeln("      move();");
document.writeln("  </script>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("    <script type=\'text/javascript\' src=\'movement.js\'>");
document.writeln("    </script>");
document.writeln("    <script type=\'text/javascript\'>");
document.writeln("       move();");
document.writeln("    </script>");
document.writeln("    <div class=\'initial\'>");
document.writeln("");
document.writeln("        <img class=\'mainbody\' src=\'../model/主体贴图/Diana_初始图.png\' width=\'350px\' height=\'350px\'>");
document.writeln("        <img class=\'frame\' src=\'../model/其他/字母边框.png\' width=\'350px\' height=\'350px\'>");
document.writeln("        <img class=\'face\' src=\'../model/其他/Diana_脸部.png\' width=\'350px\' height=\'350px\'>");
document.writeln("        <img class=\'expression\' src=\'../model/表情/3.png\'  width=\'350px\' height=\'350px\'>");
document.writeln("        <img class=\'hair\' src=\'../model/其他/Diana_前发.png\' width=\'350px\' height=\'350px\'>");
document.writeln("        <img class=\'talking\' src=\'../model/对话/想然然了没有呀.png\' width=\'350px\' height=\'350px\'>");
document.writeln("    </div>");
document.writeln("    <script>");
document.writeln("    var j = 0;");
document.writeln("    var talking = document.querySelector(\'.talking\');");
document.writeln("    var talk=document.querySelector(\'div\');");
document.writeln("    var expression=document.querySelector(\'.expression\')");
document.writeln("    talk.onclick=function(){");
document.writeln("        talking.style.display=\'block\';");
document.writeln("        talking.src=\'../model/对话/有然然陪着你呢.png\'");
document.writeln("        expression.src=\'../model/表情/Mua.png\'");
document.writeln("    }");
document.writeln("");
document.writeln("    talk.addEventListener(\'mouseenter\',function(){");
document.writeln("    talking.style.display=\'block\';");
document.writeln("    talking.src=\'../model/对话/和我一起打代码吧.png\';");
document.writeln("    expression.src=\'../model/表情/星星眼.png\'");
document.writeln("    })");
document.writeln("    var fader = setInterval(function() {");
document.writeln("        j++;");
document.writeln("        expression.src = \'../model/表情/\' + j + \'.png\';");
document.writeln("        if (j == 4)");
document.writeln("            j = 1;");
document.writeln("    }, 3000);");
document.writeln("");
document.writeln("");
document.writeln("    var fader2 = setInterval(function () {");
document.writeln("      talking.style.display=\'none\'");
document.writeln("    }, 3000);");
document.writeln("    var image = document.querySelector(\'.mainbody\');");
document.writeln("");
document.writeln("    var frame=document.querySelector(\'.frame\');");
document.writeln("    document.addEventListener(\'keyup\', function (up) {");
document.writeln("        if (up.key ==\'a\'||up.key==\'A\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'none\';");
document.writeln("        }");
document.writeln("        if (up.key == \'b\'||up.key==\'B\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'none\';");
document.writeln("        }");
document.writeln("        if (up.key == \'c\'||up.key==\'C\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'none\';");
document.writeln("        }");
document.writeln("        if (up.key == \'d\'||up.key==\'D\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'none\';");
document.writeln("        }");
document.writeln("        if (up.key == \'e\'||up.key==\'E\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'none\';");
document.writeln("        }");
document.writeln("        if (up.key == \'f\'||up.key==\'F\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'none\';");
document.writeln("        }");
document.writeln("        if (up.key ==\'g\'||up.key==\'G\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'none\';");
document.writeln("        }");
document.writeln("        if (up.key == \'h\'||up.key==\'H\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'none\';");
document.writeln("        }");
document.writeln("        if (up.key == \'i\'||up.key==\'I\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (up.key == \'j\'||up.key==\'J\') {");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("            frame.style.display=\'none\';");
document.writeln("        }");
document.writeln("        if (up.key == \'k\'||up.key==\'K\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'l\'||up.key==\'L\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'m\'||up.key==\'M\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'n\'||up.key==\'N\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'o\'||up.key==\'O\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'p\'||up.key==\'P\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'q\'||up.key==\'Q\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'r\'||up.key==\'R\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'s\'||up.key==\'S\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'t\'||up.key==\'T\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'u\'||up.key==\'U\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'v\'||up.key==\'V\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'w\'||up.key==\'W\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'x\'||up.key==\'X\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("        if (up.key == \'y\'||up.key==\'Y\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("");
document.writeln("        if (up.key == \'z\'||up.key==\'Z\') {");
document.writeln("            frame.style.display=\'none\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_初始图.png\';");
document.writeln("        }");
document.writeln("");
document.writeln("    })");
document.writeln("    document.addEventListener(\'keydown\', function (e) {");
document.writeln("        if (e.key == \'a\'||e.key==\'A\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_A.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'b\'||e.key==\'B\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_B.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'c\'||e.key==\'C\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_C.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'d\'||e.key==\'D\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_D.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'e\'||e.key==\'E\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_E.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'f\'||e.key==\'F\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_F.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'g\'||e.key==\'G\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_G.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'h\'||e.key==\'H\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_H.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'i\'||e.key==\'I\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_I.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'j\'||e.key==\'J\') {");
document.writeln("");
document.writeln("            image.src = \'../model/主体贴图/Diana_J.png\';");
document.writeln("            frame.style.display=\'block\';");
document.writeln("        }");
document.writeln("        if (e.key == \'k\'||e.key==\'K\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_K.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'l\'||e.key==\'L\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_L.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'m\'||e.key==\'M\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_M.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'n\'||e.key==\'N\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_N.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'o\'||e.key==\'O\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_O.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'p\'||e.key==\'P\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_P.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'q\'||e.key==\'Q\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_Q.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'r\'||e.key==\'R\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_R.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'s\'||e.key==\'S\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_S.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'t\'||e.key==\'T\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_T.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'u\'||e.key==\'U\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_U.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'v\'||e.key==\'V\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_v.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'w\'||e.key==\'W\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_W.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'x\'||e.key==\'X\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_X.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'y\'||e.key==\'Y\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_Y.png\';");
document.writeln("        }");
document.writeln("        if (e.key == \'z\'||e.key==\'Z\') {");
document.writeln("            frame.style.display=\'block\';");
document.writeln("            image.src = \'../model/主体贴图/Diana_Z.png\';");
document.writeln("        }");
document.writeln("    })");
document.writeln("    </script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");