

function createNode() {
    var container = document.createDocumentFragment();
    var e_0 = document.createElement("div");
    var e_1 = document.createElement("meta");
    e_1.setAttribute("charset", "UTF-8");
    e_0.appendChild(e_1);
    var e_2 = document.createElement("meta");
    e_2.setAttribute("http-equiv", "X-UA-Compatible");
    e_2.setAttribute("content", "IE=edge");
    e_0.appendChild(e_2);
    var e_3 = document.createElement("meta");
    e_3.setAttribute("name", "viewport");
    e_3.setAttribute("content", "width=device-width, initial-scale=1.0");
    e_0.appendChild(e_3);
    var e_4 = document.createElement("title");
    e_4.appendChild(document.createTextNode("Document"));
    e_0.appendChild(e_4);
    var e_5 = document.createElement("style");
    e_5.appendChild(document.createTextNode("\n.initial {\ndisplay: flex;\nposition: fixed;\ncolor: red;\nwidth: 240px;\nheight: 240px;\nleft: 75%;\nbottom: 15%;\n}\n.image {\nposition: absolute;\nleft: 200px;\n}\n.change {\ndisplay: none;\nposition: fixed;\ncolor: red;\nwidth: 240px;\nheight: 240px;\nright: 50px;\nbottom: 50px;\n}\n.mainbody {\nposition: absolute;\n}\n.expression {\nposition: absolute;\n}\n.face {\nposition: absolute;\n}\n.hair {\nposition: absolute;\n}\n.talking{\nposition:absolute;\n}\n.frame{\nposition:absolute;\ndisplay: none;\n}\n"));
    e_0.appendChild(e_5);
    var e_6 = document.createElement("script");
    e_6.setAttribute("type", "text/javascript");
    e_6.setAttribute("src", "movement.js");
    e_0.appendChild(e_6);
    e_0.appendChild(document.createTextNode(">\n"));
    var e_7 = document.createElement("script");
    e_7.setAttribute("type", "text/javascript");
    e_7.appendChild(document.createTextNode("\nmove();\n"));
    e_0.appendChild(e_7);
    var e_8 = document.createElement("script");
    e_8.setAttribute("type", "text/javascript");
    e_8.setAttribute("src", "movement.js");
    e_0.appendChild(e_8);
    var e_9 = document.createElement("script");
    e_9.setAttribute("type", "text/javascript");
    e_9.appendChild(document.createTextNode("\nmove();\n"));
    e_0.appendChild(e_9);
    var e_10 = document.createElement("div");
    e_10.setAttribute("class", "initial");
    var e_11 = document.createElement("img");
    e_11.setAttribute("class", "mainbody");
    e_11.setAttribute("src", "../model/主体贴图/Diana_初始图.png");
    e_11.setAttribute("width", "350px");
    e_11.setAttribute("height", "350px");
    e_10.appendChild(e_11);
    var e_12 = document.createElement("img");
    e_12.setAttribute("class", "frame");
    e_12.setAttribute("src", "../model/其他/字母边框.png");
    e_12.setAttribute("width", "350px");
    e_12.setAttribute("height", "350px");
    e_10.appendChild(e_12);
    var e_13 = document.createElement("img");
    e_13.setAttribute("class", "face");
    e_13.setAttribute("src", "../model/其他/Diana_脸部.png");
    e_13.setAttribute("width", "350px");
    e_13.setAttribute("height", "350px");
    e_10.appendChild(e_13);
    var e_14 = document.createElement("img");
    e_14.setAttribute("class", "expression");
    e_14.setAttribute("src", "../model/表情/3.png");
    e_14.setAttribute("width", "350px");
    e_14.setAttribute("height", "350px");
    e_10.appendChild(e_14);
    var e_15 = document.createElement("img");
    e_15.setAttribute("class", "hair");
    e_15.setAttribute("src", "../model/其他/Diana_前发.png");
    e_15.setAttribute("width", "350px");
    e_15.setAttribute("height", "350px");
    e_10.appendChild(e_15);
    var e_16 = document.createElement("img");
    e_16.setAttribute("class", "talking");
    e_16.setAttribute("src", "../model/对话/想然然了没有呀.png");
    e_16.setAttribute("width", "350px");
    e_16.setAttribute("height", "350px");
    e_10.appendChild(e_16);
    e_0.appendChild(e_10);
    var e_17 = document.createElement("script");
    e_17.appendChild(document.createTextNode("\nvar j = 0; \nvar talking = document.querySelector('.talking');\nvar talk=document.querySelector('div');\nvar expression=document.querySelector('.expression')\ntalk.onclick=function(){\ntalking.style.display='block';\ntalking.src=\"../model/对话/有然然陪着你呢.png\"\nexpression.src=\"../model/表情/Mua.png\"\n}\ntalk.addEventListener('mouseenter',function(){\ntalking.style.display='block';   \ntalking.src=\"../model/对话/和我一起打代码吧.png\";\nexpression.src=\"../model/表情/星星眼.png\"\n})\nvar fader = setInterval(function() {\nj++;\nexpression.src = \"../model/表情/\" + j + \".png\";\nif (j == 4)\nj = 1;\n}, 3000);\nvar fader2 = setInterval(function () {\ntalking.style.display='none'\n}, 3000);\nvar image = document.querySelector('.mainbody');\nvar frame=document.querySelector('.frame');\ndocument.addEventListener('keyup', function (up) {\nif (up.key =='a'||up.key=='A') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='none';\n}\nif (up.key == 'b'||up.key=='B') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='none';\n}\nif (up.key == 'c'||up.key=='C') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='none';\n}\nif (up.key == 'd'||up.key=='D') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='none';\n}\nif (up.key == 'e'||up.key=='E') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='none';\n}\nif (up.key == 'f'||up.key=='F') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='none';\n}\nif (up.key =='g'||up.key=='G') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='none';\n}\nif (up.key == 'h'||up.key=='H') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='none';\n}\nif (up.key == 'i'||up.key=='I') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='block';\n}\nif (up.key == 'j'||up.key=='J') {\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\nframe.style.display='none';\n}\nif (up.key == 'k'||up.key=='K') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'l'||up.key=='L') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'm'||up.key=='M') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'n'||up.key=='N') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'o'||up.key=='O') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'p'||up.key=='P') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'q'||up.key=='Q') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'r'||up.key=='R') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 's'||up.key=='S') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 't'||up.key=='T') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'u'||up.key=='U') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'v'||up.key=='V') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'w'||up.key=='W') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'x'||up.key=='X') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'y'||up.key=='Y') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\nif (up.key == 'z'||up.key=='Z') {\nframe.style.display='none';\nimage.src = \"../model/主体贴图/Diana_初始图.png\";\n}\n})\ndocument.addEventListener('keydown', function (e) {\nif (e.key == 'a'||e.key=='A') {\nimage.src = '../model/主体贴图/Diana_A.png';\nframe.style.display='block';\n}\nif (e.key == 'b'||e.key=='B') {\nimage.src = '../model/主体贴图/Diana_B.png';\nframe.style.display='block';\n}\nif (e.key == 'c'||e.key=='C') {\nimage.src = '../model/主体贴图/Diana_C.png';\nframe.style.display='block';\n}\nif (e.key == 'd'||e.key=='D') {\nimage.src = '../model/主体贴图/Diana_D.png';\nframe.style.display='block';\n}\nif (e.key == 'e'||e.key=='E') {\nimage.src = '../model/主体贴图/Diana_E.png';\nframe.style.display='block';\n}\nif (e.key == 'f'||e.key=='F') {\nimage.src = '../model/主体贴图/Diana_F.png';\nframe.style.display='block';\n}\nif (e.key == 'g'||e.key=='G') {\nimage.src = '../model/主体贴图/Diana_G.png';\nframe.style.display='block';\n}\nif (e.key == 'h'||e.key=='H') {\nimage.src = '../model/主体贴图/Diana_H.png';\nframe.style.display='block';\n}\nif (e.key == 'i'||e.key=='I') {\nimage.src = '../model/主体贴图/Diana_I.png';\nframe.style.display='block';\n}\nif (e.key == 'j'||e.key=='J') {\nimage.src = '../model/主体贴图/Diana_J.png';\nframe.style.display='block';\n}\nif (e.key == 'k'||e.key=='K') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_K.png';\n}\nif (e.key == 'l'||e.key=='L') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_L.png';\n}\nif (e.key == 'm'||e.key=='M') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_M.png';\n}\nif (e.key == 'n'||e.key=='N') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_N.png';\n}\nif (e.key == 'o'||e.key=='O') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_O.png';\n}\nif (e.key == 'p'||e.key=='P') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_P.png';\n}\nif (e.key == 'q'||e.key=='Q') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_Q.png';\n}\nif (e.key == 'r'||e.key=='R') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_R.png';\n}\nif (e.key == 's'||e.key=='S') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_S.png';\n}\nif (e.key == 't'||e.key=='T') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_T.png';\n}\nif (e.key == 'u'||e.key=='U') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_U.png';\n}\nif (e.key == 'v'||e.key=='V') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_v.png';\n}\nif (e.key == 'w'||e.key=='W') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_W.png';\n}\nif (e.key == 'x'||e.key=='X') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_X.png';\n}\nif (e.key == 'y'||e.key=='Y') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_Y.png';\n}\nif (e.key == 'z'||e.key=='Z') {\nframe.style.display='block';\nimage.src = '../model/主体贴图/Diana_Z.png';\n}\n})\n"));
    e_0.appendChild(e_17);
    container.appendChild(e_0);
    return container;
}